### ISSUE TITLE
Please bump NFC dependency

### ISSUE THREAD

**Issue by fuzxxl** [hsanjuan/go-nfctype4#1]
I have recently migrated `github.com/fuzxxl/nfc` to Go modules.  The new import path is

    import "github.com/fuzxxl/nfc/v2"

libnfc version 1.8.0 or newer is required.  Please consider updating your dependency as the old versioning scheme is no longer supported.

**Comment by hsanjuan** [comment]
Thank you for the heads up!

**Comment by fuzxxl** [comment]
Thanks for your quick response.  If you encounter any issues with my libnfc wrapper, please let me know by filing an issue.  I am always happy to improve my code.
