### ISSUE TITLE
Support Capability Containers with TLV Blocks

### ISSUE THREAD

**Issue by backkem** [hsanjuan/go-nfctype4#3]
It seems this assumption is causing some trouble:
https://github.com/hsanjuan/go-nfctype4/blob/fd78cb89d3499072eb1dcdb6cb051c1beb359b42/device.go#L286-L287

The Capability Container is 15 bytes as minimum but it can have TLV Blocks making it longer; 23 bytes in my case. This makes cc.Unmarshal fail because it uses cc.CCLEN for parsing, causing it to try reading beyond the 15 bytes.

I'm not sure what the best fix is yet: supporting the truncated Capability Container in cc.Unmarshal or refactoring to read the entire Capability Container file.

**Comment by hsanjuan** [comment]
At first sight it seems to be that we should parse CCLEN first, and then read as many bytes, and then unmarshal it all. How does that sound?
